authorizations: &AUTHORIZATIONS
  ## Authorization
  group_base: ou=groups,dc=test,dc=com
  required_groups:
    - cn=admins,ou=groups,dc=test,dc=com
  allowed_groups: "test_group_one test_group_two"
  require_attribute:
    objectClass: inetOrgPerson
    authorizationRole: blogAdmin

test:
  host: localhost
  port: 3389
  attribute: uid
  base: ou=people,dc=test,dc=com
  admin_user: cn=admin,dc=test,dc=com
  admin_password: secret
  ssl: false
  <<: *AUTHORIZATIONS
