<% @base = "dc=test,dc=com" %>

authorizations: &AUTHORIZATIONS
  ## Authorization
  group_base: <%= "ou=groups,#{@base}" %>
  required_groups:
    - cn=admins,<%= "ou=groups,#{@base}" %>
  allowed_groups: "test_group_one test_group_two"
  require_attribute:
    objectClass: inetOrgPerson
    authorizationRole: blogAdmin

test: &TEST
  host: <%= "localhost" %>
  port: 3389
  attribute: cn
  base: <%= "ou=people,#{@base}" %>
  admin_user: <%= "cn=admin,#{@base}" %>
  admin_password: secret
  ssl: true
  <<: *AUTHORIZATIONS

development:
  <<: *TEST
